### ISSUE TITLE
Behaviour with -q and -c options

### ISSUE THREAD

**Issue by deenar** [Beuth-Erdelt/DBMS-Benchmarker#122]
Currently the benchmarker 
1) opens connections to all databases defined in the connections file even though the -c option is passed in.
2) runs through each and every query defined in the queries file, even though -q option is specified.

It would be good if the benchmarker only used to connection and query specified on the command line

**Comment by perdelt** [comment]
It works on my side. Could you provide more information?

**Comment by deenar** [comment]
It works but connects to all the databases in the connections file and does it for all the queries in the queries file.

`C:>python .\benchmark.py run  -cf .\config\connections.config -qf .\example\tpc-h\queries.config -b --num-run 1 -q 8 -c Exadata
Benchmarking in folder 1686119940
More active connections from 0 to 1 for Exadata
Establish global connection #0
Closed connection for Exadata
More active connections from 0 to 1 for PostgreSQL
Establish global connection #0
Closed connection for PostgreSQL
More active connections from 0 to 1 for PostgresFlexi
Establish global connection #0
Closed connection for PostgresFlexi
More active connections from 0 to 1 for SQLServer
Establish global connection #0
Closed connection for SQLServer
More active connections from 0 to 1 for Synapse
Establish global connection #0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Closed connection for Synapse
More active connections from 0 to 1 for Exadata
Establish global connection #0
Closed connection for Exadata
More active connections from 0 to 1 for PostgreSQL
Establish global connection #0
Closed connection for PostgreSQL
More active connections from 0 to 1 for PostgresFlexi
Establish global connection #0
Closed connection for PostgresFlexi
More active connections from 0 to 1 for SQLServer
Establish global connection #0
Closed connection for SQLServer
More active connections from 0 to 1 for Synapse
Establish global connection #0
Closed connection for Synapse
More active connections from 0 to 1 for Exadata
Establish global connection #0
Closed connection for Exadata
More active connections from 0 to 1 for PostgreSQL
Establish global connection #0
Closed connection for PostgreSQL
More active connections from 0 to 1 for PostgresFlexi
Establish global connection #0
Closed connection for PostgresFlexi
More active connections from 0 to 1 for SQLServer
Establish global connection #0
Closed connection for SQLServer
More active connections from 0 to 1 for Synapse
Establish global connection #0
Closed connection for Synapse
...
More active connections from 0 to 1 for Exadata
Establish global connection #0
INFO:benchmarker:Starting benchmarks of Q8 at dbms Exadata
Benchmarking Q8: National Market Share (TPC-H Q8)
Connection: Exadata
numRun 1: execution [ms]: 462.3612000000037
numRun 1: transfer [ms]: 4.874700000002008
numRun 1: Size of result list retrieved: 88 bytes
INFO:singleResult:numRun 1: Size of processed result list retrieved: 96 bytes
Closed connection for Exadata
More active connections from 0 to 1 for PostgreSQL
Establish global connection #0
Closed connection for PostgreSQL
More active connections from 0 to 1 for PostgresFlexi
Establish global connection #0
Closed connection for PostgresFlexi
More active connections from 0 to 1 for SQLServer
Establish global connection #0
Closed connection for SQLServer
More active connections from 0 to 1 for Synapse
Establish global connection #0
Closed connection for Synapse

...
Establish global connection #0
Closed connection for Synapse
DBMSBenchmarker duration: 67
Report printer
Q8: National Market Share (TPC-H Q8) - timerExecution
+-------------+------+--------+---------+--------+----------+-------+----------+--------+--------+
| DBMS [ms]   |    n |   mean |   stdev |   cv % |   qcod % |   iqr |   median |    min |    max |
+=============+======+========+=========+========+==========+=======+==========+========+========+
| Exadata     | 1.00 | 462.36 |    0.00 |   0.00 |     0.00 |  0.00 |   462.36 | 462.36 | 462.36 |
+-------------+------+--------+---------+--------+----------+-------+----------+--------+--------+
Experiment 1686119940 has been finished
`

**Comment by perdelt** [comment]
Thanks for sharing! Yes, that is a unexpected behaviour. It will be fixed with the next release #117
